/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uı;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Attendance;
public class AttendanceFrame extends javax.swing.JFrame {

    /**
     * Creates new form AttendanceFrame
     */
    public AttendanceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAttDate = new javax.swing.JTextField();
        txtCourseId = new javax.swing.JTextField();
        txtStudentId = new javax.swing.JTextField();
        txtAttId = new javax.swing.JTextField();
        btnAddAttendance = new javax.swing.JButton();
        btnEditAttendance = new javax.swing.JButton();
        btnDeleteAttendance = new javax.swing.JButton();
        btnListAllAttendances = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendances = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Attendance Management");

        jLabel2.setText("Attendance ID:");

        jLabel3.setText("Student ID:");

        jLabel4.setText("Course ID:");

        jLabel5.setText("Attendance Date:");

        btnAddAttendance.setText("Add");
        btnAddAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAttendanceActionPerformed(evt);
            }
        });

        btnEditAttendance.setText("Edit");
        btnEditAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAttendanceActionPerformed(evt);
            }
        });

        btnDeleteAttendance.setText("Delete");
        btnDeleteAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAttendanceActionPerformed(evt);
            }
        });

        btnListAllAttendances.setText("List");
        btnListAllAttendances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllAttendancesActionPerformed(evt);
            }
        });

        btnBackup.setText("Backup");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnRestore.setText("Restore");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        btnBackToMenu.setText("Main Menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        tblAttendances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Attendance ID:", "Student ID:", "Course ID:", "Attendance Date"
            }
        ));
        jScrollPane1.setViewportView(tblAttendances);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAttId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAttDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListAllAttendances)
                            .addComponent(btnDeleteAttendance)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddAttendance)
                                    .addComponent(btnEditAttendance))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRestore)
                                    .addComponent(btnBackup)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBackToMenu)
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBackToMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAttId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAttendance)
                    .addComponent(btnBackup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAttendance)
                    .addComponent(btnRestore))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAttendance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAttDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAllAttendances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshAttendancesTable() {
    // Tabloyu almak
    DefaultTableModel model = (DefaultTableModel) tblAttendances.getModel();
    
    // Mevcut verileri temizlemek
    model.setRowCount(0); // Tabloyu temizler
    
    // Attendance verilerini tabloya eklemek
    for (Attendance attendance : Attendance.attendances) {
        model.addRow(new Object[]{
            attendance.getAttId(),       // Attendance ID
            attendance.getStdId(),       // Student ID
            attendance.getCrsId(),       // Course ID
            attendance.getAttDate()      // Attendance Date
        });
    }
}

    private void btnAddAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAttendanceActionPerformed
    // Attendance ekleme işlemini doğrudan burada gerçekleştireceğiz.
    int attId = Integer.parseInt(txtAttId.getText());  // Attendance ID
    int stdId = Integer.parseInt(txtStudentId.getText());  // Student ID
    int crsId = Integer.parseInt(txtCourseId.getText());  // Course ID
    String attDate = txtAttDate.getText();  // Attendance Date

    // Attendance ekle
    Attendance.addAttendance(attId, stdId, crsId, attDate);

    JOptionPane.showMessageDialog(this, "Attendance added successfully!");
    refreshAttendancesTable();  // Tabloyu güncelle
    }//GEN-LAST:event_btnAddAttendanceActionPerformed

    private void btnEditAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAttendanceActionPerformed

    int attId = Integer.parseInt(txtAttId.getText());  // Attendance ID
    int stdId = Integer.parseInt(txtStudentId.getText());  // Student ID
    int crsId = Integer.parseInt(txtCourseId.getText());  // Course ID
    String attDate = txtAttDate.getText();  // Attendance Date

    // Attendance düzenle
    Attendance.editAttendance(attId, stdId, crsId, attDate);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Attendance updated successfully!");
    refreshAttendancesTable();  // Tabloyu güncelle
    }//GEN-LAST:event_btnEditAttendanceActionPerformed

    private void btnDeleteAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAttendanceActionPerformed
   // Tablodan seçilen satırı kontrol edin
    int selectedRow = tblAttendances.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an attendance record to delete!");
        return;
    }

    // Seçilen satırın ID değerini alın
    DefaultTableModel model = (DefaultTableModel) tblAttendances.getModel();
    int attId = (int) model.getValueAt(selectedRow, 0);  // Attendance ID

    // Attendance listesinden bu ID'yi silin
    Attendance.deleteAttendance(attId);

    // Tablodan satırı kaldırın
    model.removeRow(selectedRow);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Attendance deleted successfully!");
    }//GEN-LAST:event_btnDeleteAttendanceActionPerformed

    private void btnListAllAttendancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllAttendancesActionPerformed
   // Mevcut tabloyu temizleyelim
    DefaultTableModel model = (DefaultTableModel) tblAttendances.getModel();
    model.setRowCount(0); // Eski verileri temizle

    // Attendance verilerini tabloya ekleyelim
    for (Attendance attendance : Attendance.attendances) {
        model.addRow(new Object[]{
            attendance.getAttId(),      // Attendance ID
            attendance.getStdId(),      // Student ID
            attendance.getCrsId(),      // Course ID
            attendance.getAttDate()     // Attendance Date
        });
    }
    }//GEN-LAST:event_btnListAllAttendancesActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
    // Attendance verilerini yedekle
    Attendance.backupAttendances();  // Verileri dosyaya kaydeder

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Backup completed successfully!");
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
   // Verileri dosyadan geri yükle
    Attendance.restoreAttendances();  // Verileri dosyadan geri yükler

    // Tablodaki verileri güncelle
    DefaultTableModel model = (DefaultTableModel) tblAttendances.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    // Attendances verilerini tabloya ekle
    for (Attendance attendance : Attendance.attendances) {
        model.addRow(new Object[]{
            attendance.getAttId(),   // Attendance ID
            attendance.getStdId(),   // Student ID
            attendance.getCrsId(),   // Course ID
            attendance.getAttDate()  
        });
    }

    JOptionPane.showMessageDialog(this, "Restore completed successfully!");
    }//GEN-LAST:event_btnRestoreActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
    btnBackToMenu.addActionListener(e -> {
    MainMenu mainMenu = new MainMenu();
    mainMenu.setVisible(true);
    dispose();
});
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAttendance;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnDeleteAttendance;
    private javax.swing.JButton btnEditAttendance;
    private javax.swing.JButton btnListAllAttendances;
    private javax.swing.JButton btnRestore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAttendances;
    private javax.swing.JTextField txtAttDate;
    private javax.swing.JTextField txtAttId;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
