/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uı;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Course;
public class CourseFrame extends javax.swing.JFrame {

    /**
     * Creates new form CourseFrame
     */
    public CourseFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCrsId = new javax.swing.JTextField();
        txtDeptId = new javax.swing.JTextField();
        txtCrsCode = new javax.swing.JTextField();
        txtCrsName = new javax.swing.JTextField();
        btnAddCourse = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnListAllCourses = new javax.swing.JButton();
        btnBackupCourses = new javax.swing.JButton();
        btnRestoreCourses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course Management");

        jLabel2.setText("Course ID:");

        jLabel3.setText("Department ID:");

        jLabel4.setText("Course Name:");

        jLabel5.setText("Course Code:");

        txtCrsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrsNameActionPerformed(evt);
            }
        });

        btnAddCourse.setText("Add");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnBackToMenu.setText("Main Menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnEditCourse.setText("Edit");
        btnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnListAllCourses.setText("List");
        btnListAllCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllCoursesActionPerformed(evt);
            }
        });

        btnBackupCourses.setText("Backup");
        btnBackupCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupCoursesActionPerformed(evt);
            }
        });

        btnRestoreCourses.setText("Restore");
        btnRestoreCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreCoursesActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Department ID", "Course Code", "Course Name"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnBackToMenu)
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCrsId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtDeptId)
                            .addComponent(txtCrsCode)
                            .addComponent(txtCrsName))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddCourse)
                            .addComponent(btnEditCourse)
                            .addComponent(btnDeleteCourse)
                            .addComponent(btnListAllCourses))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackupCourses)
                            .addComponent(btnRestoreCourses)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackToMenu)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCrsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnBackupCourses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCourse)
                    .addComponent(btnRestoreCourses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCrsCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCrsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAllCourses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCrsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrsNameActionPerformed
private void refreshCoursesTable() {
    // Tabloyu al
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    // Course listesindeki tüm dersleri tabloya ekleyin
    for (Course course : Course.courses) {
        model.addRow(new Object[]{
            course.getCrsId(),
            course.getDeptId(),
            course.getCrsCode(),
            course.getCrsName()
        });
    }
}



    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
    // Tıklama işlevini doğrudan burada tanımlıyoruz
    int crsId = Integer.parseInt(txtCrsId.getText());
    int deptId = Integer.parseInt(txtDeptId.getText());
    String crsCode = txtCrsCode.getText();
    String crsName = txtCrsName.getText();

    // Ders ekle
    Course.addCourse(crsId, deptId, crsCode, crsName);

    // Kullanıcıya başarı mesajı
    JOptionPane.showMessageDialog(this, "Course added successfully!");
    refreshCoursesTable();  // Tabloyu güncelle
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCourseActionPerformed
    // Ders düzenleme işlemi
    int crsId = Integer.parseInt(txtCrsId.getText());
    int deptId = Integer.parseInt(txtDeptId.getText());
    String crsCode = txtCrsCode.getText();
    String crsName = txtCrsName.getText();

    // Ders düzenle
    Course.editCourse(crsId, deptId, crsCode, crsName);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Course updated successfully!");

    // Tabloyu güncelle
    refreshCoursesTable();  // Tabloyu güncelle
    }//GEN-LAST:event_btnEditCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
   // Tablodan seçilen satırı kontrol et
    int selectedRow = tblCourses.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course to delete!");
        return;
    }

    // Seçilen satırın ID değerini al
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    int crsId = (int) model.getValueAt(selectedRow, 0);

    // Course listesinden bu ID'yi sil
    Course.deleteCourse(crsId);

    // Tablodan satırı kaldır
    model.removeRow(selectedRow);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Course deleted successfully!");
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnListAllCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllCoursesActionPerformed
    // Tabloyu al
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0); // Eski verileri temizle

    // Course listesindeki tüm dersleri tabloya ekleyin
    for (Course course : Course.courses) {
        model.addRow(new Object[]{
            course.getCrsId(),
            course.getDeptId(),
            course.getCrsCode(),
            course.getCrsName()
        });
    }
    }//GEN-LAST:event_btnListAllCoursesActionPerformed

    private void btnBackupCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupCoursesActionPerformed
    // Dersleri dosyaya yedekle
    Course.backupCourses();  // Verileri dosyaya kaydeder
    JOptionPane.showMessageDialog(this, "Backup completed successfully!");        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackupCoursesActionPerformed

    private void btnRestoreCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreCoursesActionPerformed
    // Verileri dosyadan geri yükle
    Course.restoreCourses();  // Yedeklenen verileri geri yükler

    // Tablodaki verileri güncelle
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    // Kursları tabloya ekle
    for (Course course : Course.courses) {
        model.addRow(new Object[]{
            course.getCrsId(),
            course.getDeptId(),
            course.getCrsCode(),
            course.getCrsName()
        });
    }

    JOptionPane.showMessageDialog(this, "Restore completed successfully!");
    }//GEN-LAST:event_btnRestoreCoursesActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        // TODO add your handling code here:
    btnBackToMenu.addActionListener(e -> {
    MainMenu mainMenu = new MainMenu();
    mainMenu.setVisible(true);
    dispose();
});        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackupCourses;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnListAllCourses;
    private javax.swing.JButton btnRestoreCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtCrsCode;
    private javax.swing.JTextField txtCrsId;
    private javax.swing.JTextField txtCrsName;
    private javax.swing.JTextField txtDeptId;
    // End of variables declaration//GEN-END:variables
}
