/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uı;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Department;
public class DepartmentFrame extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentFrame
     */
    public DepartmentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDeptId = new javax.swing.JTextField();
        txtDeptName = new javax.swing.JTextField();
        btnAddDepartment = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        btnEditDepartment = new javax.swing.JButton();
        btnDeleteDepartment = new javax.swing.JButton();
        btnListAllDepartments = new javax.swing.JButton();
        btnBackupDepartments = new javax.swing.JButton();
        btnRestoreDepartments = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Department Managemant");

        jLabel2.setText("Department ID:");

        jLabel3.setText("Department Name:");

        btnAddDepartment.setText("Add Department");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        btnBackToMenu.setText("Main Menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnEditDepartment.setText("Edit Department");
        btnEditDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDepartmentActionPerformed(evt);
            }
        });

        btnDeleteDepartment.setText("Delete Department");
        btnDeleteDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDepartmentActionPerformed(evt);
            }
        });

        btnListAllDepartments.setText("List All");
        btnListAllDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllDepartmentsActionPerformed(evt);
            }
        });

        btnBackupDepartments.setText("Backup");
        btnBackupDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupDepartmentsActionPerformed(evt);
            }
        });

        btnRestoreDepartments.setText("Restore");
        btnRestoreDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreDepartmentsActionPerformed(evt);
            }
        });

        tblDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Department ID", "Department Name"
            }
        ));
        jScrollPane1.setViewportView(tblDepartments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBackToMenu)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeptId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtDeptName))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddDepartment)
                                .addGap(29, 29, 29)
                                .addComponent(btnDeleteDepartment))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditDepartment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListAllDepartments)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackupDepartments)
                            .addComponent(btnRestoreDepartments)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBackToMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDepartment)
                    .addComponent(btnDeleteDepartment)
                    .addComponent(btnBackupDepartments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditDepartment)
                    .addComponent(btnListAllDepartments)
                    .addComponent(btnRestoreDepartments))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshDepartmentsTable() {
    // Tabloyu al
    DefaultTableModel model = (DefaultTableModel) tblDepartments.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    // Department listesindeki tüm departmanları tabloya ekleyin
    for (Department department : Department.departments) {
        model.addRow(new Object[]{
            department.getDeptId(),
            department.getDeptName()
        });
    }
}

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
  // Öğrenci ekleme işlemi
    int deptId = Integer.parseInt(txtDeptId.getText());
    String deptName = txtDeptName.getText();

    // Department ekle
    Department.addDepartment(deptId, deptName);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Department added successfully!");

    // Tabloyu güncelle
    refreshDepartmentsTable();  // Tabloyu yenile
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnEditDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDepartmentActionPerformed
    // Öğrenci düzenleme işlemi
    int deptId = Integer.parseInt(txtDeptId.getText());
    String deptName = txtDeptName.getText();

    // Department düzenle
    Department.editDepartment(deptId, deptName);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Department updated successfully!");

    // Tabloyu güncelle
    refreshDepartmentsTable();  // Tabloyu yenile
    }//GEN-LAST:event_btnEditDepartmentActionPerformed

    private void btnDeleteDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDepartmentActionPerformed
    // Tablodan seçilen satırı kontrol et
    int selectedRow = tblDepartments.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a department to delete!");
        return;
    }

    // Seçilen satırın Department ID değerini al
    DefaultTableModel model = (DefaultTableModel) tblDepartments.getModel();
    int deptId = (int) model.getValueAt(selectedRow, 0);

    // Department listesinden bu ID'yi sil
    Department.deleteDepartment(deptId);

    // Tablodan satırı kaldır
    model.removeRow(selectedRow);

    // Başarı mesajı
    JOptionPane.showMessageDialog(this, "Department deleted successfully!");
    }//GEN-LAST:event_btnDeleteDepartmentActionPerformed

    private void btnListAllDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllDepartmentsActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblDepartments.getModel();
    model.setRowCount(0); // Eski verileri temizle

    // Department listesindeki tüm departmanları tabloya ekleyin
    for (Department department : Department.departments) {
        model.addRow(new Object[]{
            department.getDeptId(),
            department.getDeptName()
        });
    }    }//GEN-LAST:event_btnListAllDepartmentsActionPerformed

    private void btnBackupDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupDepartmentsActionPerformed
  Department.backupDepartments(); // Verileri dosyaya kaydeder
    JOptionPane.showMessageDialog(this, "Backup completed successfully!");        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackupDepartmentsActionPerformed

    private void btnRestoreDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreDepartmentsActionPerformed
    // Verileri dosyadan geri yükle
    Department.restoreDepartments(); 

    // Tablodaki verileri güncelle
    DefaultTableModel model = (DefaultTableModel) tblDepartments.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    // Departmanları tabloya ekle
    for (Department department : Department.departments) {
        model.addRow(new Object[]{
            department.getDeptId(),
            department.getDeptName()
        });
    }

    JOptionPane.showMessageDialog(this, "Restore completed successfully!");
    }//GEN-LAST:event_btnRestoreDepartmentsActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
    btnBackToMenu.addActionListener(e -> {
    MainMenu mainMenu = new MainMenu();
    mainMenu.setVisible(true);
    dispose(); // StudentFrame'i kapat
});
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackupDepartments;
    private javax.swing.JButton btnDeleteDepartment;
    private javax.swing.JButton btnEditDepartment;
    private javax.swing.JButton btnListAllDepartments;
    private javax.swing.JButton btnRestoreDepartments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDepartments;
    private javax.swing.JTextField txtDeptId;
    private javax.swing.JTextField txtDeptName;
    // End of variables declaration//GEN-END:variables
}
