package uı;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Course;
import java.sql.Date;
import java.util.List;
public class CourseFrame extends javax.swing.JFrame {

    /**
     * Creates new form CourseFrame
     */
    public CourseFrame() {
        initComponents();
        refreshCoursesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDeptId = new javax.swing.JTextField();
        txtCrsCode = new javax.swing.JTextField();
        txtCrsName = new javax.swing.JTextField();
        btnAddCourse = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnListAllCourses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course Management");

        jLabel3.setText("Department ID:");

        jLabel4.setText("Course Name:");

        jLabel5.setText("Course Code:");

        txtCrsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrsNameActionPerformed(evt);
            }
        });

        btnAddCourse.setText("Add");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnBackToMenu.setText("Main Menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnEditCourse.setText("Edit");
        btnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnListAllCourses.setText("List");
        btnListAllCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllCoursesActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Department ID", "Course Code", "Course Name"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCrsName)
                        .addGap(398, 398, 398))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeptId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCourse)
                            .addComponent(btnEditCourse))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListAllCourses)
                            .addComponent(btnDeleteCourse))
                        .addGap(203, 203, 203))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnBackToMenu)
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel1)
                            .addGap(138, 138, 138))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnBackToMenu)
                            .addGap(123, 123, 123)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDeptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCrsCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCourse)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditCourse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteCourse)
                                .addGap(18, 18, 18)
                                .addComponent(btnListAllCourses)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCrsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCrsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrsNameActionPerformed
private void refreshCoursesTable() {
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0); // Mevcut tabloyu temizle

    try {
        List<Course> courses = Course.getAllCourses(); // SQL üzerinden verileri getir
        for (Course course : courses) {
            model.addRow(new Object[]{
                course.getCrsId(),     // Course ID
                course.getDeptId(),    // Department ID
                course.getCrsCode(),   // Course Code
                course.getCrsName()    // Course Name
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error fetching courses data: " + e.getMessage());
    }
}



    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
    try {
        int deptId = Integer.parseInt(txtDeptId.getText());
        String crsCode = txtCrsCode.getText();
        String crsName = txtCrsName.getText();

        // SQL ile Course ekle
        Course.addCourse(deptId, crsCode, crsName);

        JOptionPane.showMessageDialog(this, "Course added successfully!");
        refreshCoursesTable(); // Tabloyu güncelle
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding course: " + e.getMessage());
    }

    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCourseActionPerformed
    try {
        int selectedRow = tblCourses.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to edit!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        int crsId = (int) model.getValueAt(selectedRow, 0); // Seçilen satırdaki Course ID'yi al
        int deptId = Integer.parseInt(txtDeptId.getText());
        String crsCode = txtCrsCode.getText();
        String crsName = txtCrsName.getText();

        // SQL ile Course düzenle
        Course.editCourse(crsId, deptId, crsCode, crsName);

        JOptionPane.showMessageDialog(this, "Course updated successfully!");
        refreshCoursesTable(); // Tabloyu güncelle
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating course: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        int selectedRow = tblCourses.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete!");
            return;
        }

        try {
            DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
            int crsId = (int) model.getValueAt(selectedRow, 0);

            // SQL ile Course sil
            Course.deleteCourse(crsId);

            JOptionPane.showMessageDialog(this, "Course deleted successfully!");
            refreshCoursesTable(); // Tabloyu güncelle
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting course: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnListAllCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllCoursesActionPerformed
refreshCoursesTable();
    }//GEN-LAST:event_btnListAllCoursesActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        // TODO add your handling code here:
    btnBackToMenu.addActionListener(e -> {
    MainMenu mainMenu = new MainMenu();
    mainMenu.setVisible(true);
    dispose();
});        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnListAllCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtCrsCode;
    private javax.swing.JTextField txtCrsName;
    private javax.swing.JTextField txtDeptId;
    // End of variables declaration//GEN-END:variables
}
